name: build-and-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: Clone and Build
        run: |
          npm install
          npm install -g gulp-cli
          if grep --color=always -rE '(Symbiflow|simbi[fF]low)' source/; then
            echo "Found incorrect casing of SymbiFlow"
            exit 1
          fi
          gulp build
      - uses: actions/upload-artifact@v2
        with:
          name: website-build
          path: build

  deploy:
    if: github.event_name == 'push'
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: website-build
          path: /tmp/website-build
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy website
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: ./.github/deploy.sh
